# Install Elasticsearch on Docker:
# https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html

# Elasticsearch Docker image:
# docker pull docker.elastic.co/elasticsearch/elasticsearch:5.5.2

From centos:7
Maintainer Andrew Kuttor <andrew.kuttor@dimensiondata.com>





